name: TWM CI

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:22-alpine

    steps:
      - name: Install git #necesitamos git para el test reporter
        run: apk add --no-cache git
      - uses: actions/checkout@v3
      - name: Git Workaround
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Install dependencies
        run: |
          npm ci
      - name: Run tests
        run: |
          npm test
      - name: Test Report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }} # run this step even if previous step failed
        with:
          name: JEST Tests # Name of the check run which will be created
          path: reports/junit.xml # Path to test results
          reporter: jest-junit # Format of test results


      # MIRAR REPO PACO
      #- name:
      #- uses: ArtiomTr/jest-coverage-report-action@v2
      #  with:
      #    coverage-file: ./coverage/report.json
      #    base-coverage-file: ./coverage/master/report.json
